# -*- coding: utf-8 -*-
"""
服务端 Luban 二进制流一键生成脚本。

作用：
  1. 运行 Luban（cs-bin 代码 + bin 二进制）生成到临时目录；
  2. 把生成的 .cs 拷贝到 Server/Network/LubanManager/Codes/，.bytes 拷贝到 Tb/；
  3. 自动重建合并版 Tables.cs（保留手工维护的 TbSkillInfo 表 + 本次 Luban 生成的所有表）；
  4. 增量更新 Server/Network/Network.csproj（自动补 Compile / Content 项）。

用法：
  cd LubanConfig/MiniTemplate
  python gen_server.py

说明：
  - SkillInfo 相关代码（SkillInfo.cs / TbSkillInfo.cs）是旧项目手工迁移、schema 已丢失，
    本脚本不重新生成、也不删除它们，只在合并 Tables.cs 时固定保留 TbSkillInfo 表。
  - vector2/vector3/vector4 是 builtin.xml 的占位 bean，服务端未引用，自动过滤。
  - 生成的 Tables.cs 仅含「Luban 本次产出的表」，SkillInfo 表在合并阶段由脚本注入。
"""

import os
import re
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET

# ---- 路径配置 ----
HERE = os.path.dirname(os.path.abspath(__file__))                     # .../LubanConfig/MiniTemplate
LUBAN_EXE = os.path.join(HERE, "Luban", "Luban.exe")
LUBAN_CONF = os.path.join(HERE, "luban.conf")

# 服务端目标目录（相对 MiniTemplate 向上 2 级到仓库根，再进 Server）
REPO_ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
SERVER_NETWORK = os.path.join(REPO_ROOT, "Server", "Network")
CODES_DIR = os.path.join(SERVER_NETWORK, "LubanManager", "Codes")
TB_DIR = os.path.join(SERVER_NETWORK, "LubanManager", "Tb")
CSPROJ = os.path.join(SERVER_NETWORK, "Network.csproj")

# 临时输出目录（脚本结束后删除）
TMP_DIR = os.path.join(REPO_ROOT, "_luban_server_tmp")
TMP_CODE = os.path.join(TMP_DIR, "code")
TMP_DATA = os.path.join(TMP_DIR, "data")

# 需要过滤、不拷贝到服务端的生成文件
SKIP_CODE_FILES = {"Tables.cs"}            # Tables.cs 由本脚本合并重建
SKIP_CODE_PREFIXES = ("vector",)           # vector2/3/4 占位 bean，服务端未引用

# 手工维护、不参与重新生成、但必须始终保留在合并 Tables 里的表
# 格式：property 名 -> loader 文件名（即 Tb 目录下 .bytes 的名字，不含后缀）
MANUAL_TABLES = {
    "TbSkillInfo": "tbskillinfo",
}


def run(cmd, cwd):
    print(">> " + " ".join(cmd))
    r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, encoding="utf-8", errors="replace")
    if r.stdout:
        print(r.stdout)
    if r.returncode != 0:
        print("!! Luban 执行失败：")
        print(r.stderr)
        sys.exit(1)


def parse_generated_tables(tables_cs_path):
    """从 Luban 生成的 Tables.cs 里解析出 (property 名, loader 文件名) 列表，保持声明顺序。"""
    txt = open(tables_cs_path, "r", encoding="utf-8").read()
    # property 声明： public TbXxx Xxx {get; }
    props = re.findall(r"public\s+(\w+)\s+(\w+)\s*\{get;\s*\}", txt)
    # 构造函数里的 new： Name = new TbXxx(loader("file"));
    loaders = re.findall(r'loader\("(\w+)"\)', txt)
    if len(props) != len(loaders):
        raise RuntimeError("Tables.cs 解析失败：property 数(%d) 与 loader 数(%d) 不一致" % (len(props), len(loaders)))
    return [(p[1], loaders[i]) for i, p in enumerate(props)]


def build_merged_tables(all_tables):
    """all_tables: [(property, loader_file), ...]，含手工表 + Luban 表，按声明顺序。"""
    props = "\n".join("    public %s %s {get; }" % (p, p) for p, _ in all_tables)
    news = "\n".join('        %s = new %s(loader("%s"));' % (p, p, f) for p, f in all_tables)
    resolves = "\n".join("        %s.ResolveRef(this);" % p for p, _ in all_tables)
    return (
        "//------------------------------------------------------------------------------\n"
        "// <auto-generated>\n"
        "//     此文件由 gen_server.py 自动合并生成（Luban 表 + 手工 SkillInfo 表）。\n"
        "// </auto-generated>\n"
        "//------------------------------------------------------------------------------\n"
        "\n"
        "using Luban;\n"
        "\n"
        "namespace cfg\n"
        "{\n"
        "public partial class Tables\n"
        "{\n"
        + props + "\n"
        "\n"
        "    public Tables(System.Func<string, ByteBuf> loader)\n"
        "    {\n"
        + news + "\n"
        "        ResolveRef();\n"
        "    }\n"
        "    \n"
        "    private void ResolveRef()\n"
        "    {\n"
        + resolves + "\n"
        "    }\n"
        "}\n"
        "\n"
        "}\n"
    )


def update_csproj(code_files, data_files):
    """增量更新 Network.csproj：补 Compile（Codes）与 Content（Tb）。"""
    ns = "http://schemas.microsoft.com/developer/msbuild/2003"
    ET.register_namespace("", ns)
    tree = ET.parse(CSPROJ)
    root = tree.getroot()

    existing_compile = set()
    existing_content = set()
    for ig in root.findall("{%s}ItemGroup" % ns):
        for c in ig.findall("{%s}Compile" % ns):
            existing_compile.add(c.get("Include"))
        for c in ig.findall("{%s}Content" % ns):
            existing_content.add(c.get("Include"))

    itemgroups = root.findall("{%s}ItemGroup" % ns)
    if not itemgroups:
        raise RuntimeError("Network.csproj 中未找到 ItemGroup")

    added_compile = []
    added_content = []

    for f in code_files:
        include = "LubanManager\\Codes\\" + f.replace("/", "\\")
        if include in existing_compile:
            continue
        e = ET.SubElement(itemgroups[-1], "Compile")
        e.set("Include", include)
        added_compile.append(include)

    for f in data_files:
        include = "LubanManager\\Tb\\" + f.replace("/", "\\")
        if include in existing_content:
            continue
        e = ET.SubElement(itemgroups[-1], "Content")
        e.set("Include", include)
        sub = ET.SubElement(e, "CopyToOutputDirectory")
        sub.text = "PreserveNewest"
        added_content.append(include)

    if added_compile or added_content:
        tree.write(CSPROJ, encoding="utf-8", xml_declaration=True)
        print("  [csproj] 新增 Compile: %s" % (added_compile or "无"))
        print("  [csproj] 新增 Content: %s" % (added_content or "无"))
    else:
        print("  [csproj] 无变化")


def main():
    # 0. 清理并准备临时目录
    if os.path.exists(TMP_DIR):
        shutil.rmtree(TMP_DIR)
    os.makedirs(TMP_CODE)
    os.makedirs(TMP_DATA)

    # 1. 运行 Luban
    print("== 1. 运行 Luban 生成 (server / cs-bin / bin) ==")
    run([
        LUBAN_EXE, "-t", "server", "-c", "cs-bin", "-d", "bin",
        "--conf", LUBAN_CONF,
        "-x", "outputCodeDir=" + TMP_CODE,
        "-x", "outputDataDir=" + TMP_DATA,
    ], cwd=HERE)

    # 2. 解析本次生成的表
    gen_tables_cs = os.path.join(TMP_CODE, "Tables.cs")
    if not os.path.exists(gen_tables_cs):
        print("!! 未找到生成的 Tables.cs，请检查 Luban 是否成功生成")
        sys.exit(1)
    luban_tables = parse_generated_tables(gen_tables_cs)
    print("== 2. 本次 Luban 生成 %d 张表：%s ==" % (len(luban_tables), [p for p, _ in luban_tables]))

    # 3. 拷贝生成的 .cs 到 Codes/（跳过 Tables.cs 与 vector 占位）
    print("== 3. 拷贝代码到 Codes/ ==")
    copied_cs = []
    for fn in sorted(os.listdir(TMP_CODE)):
        if not fn.endswith(".cs"):
            continue
        if fn in SKIP_CODE_FILES or fn.startswith(SKIP_CODE_PREFIXES):
            print("  [跳过] %s" % fn)
            continue
        shutil.copyfile(os.path.join(TMP_CODE, fn), os.path.join(CODES_DIR, fn))
        copied_cs.append(fn)
        print("  [拷贝] %s" % fn)

    # 4. 拷贝 .bytes 到 Tb/
    print("== 4. 拷贝二进制到 Tb/ ==")
    copied_bytes = []
    for fn in sorted(os.listdir(TMP_DATA)):
        if not fn.endswith(".bytes"):
            continue
        shutil.copyfile(os.path.join(TMP_DATA, fn), os.path.join(TB_DIR, fn))
        copied_bytes.append(fn)
        print("  [拷贝] %s" % fn)

    # 5. 重建合并版 Tables.cs（手工表 + Luban 表，手工表在前保持向后兼容）
    print("== 5. 重建合并版 Tables.cs ==")
    all_tables = [(p, f) for p, f in MANUAL_TABLES.items()] + luban_tables
    merged = build_merged_tables(all_tables)
    with open(os.path.join(CODES_DIR, "Tables.cs"), "w", encoding="utf-8") as fp:
        fp.write(merged)
    print("  [写入] Tables.cs 含表: %s" % [p for p, _ in all_tables])

    # 6. 更新 csproj
    print("== 6. 更新 Network.csproj ==")
    update_csproj(copied_cs, copied_bytes)

    # 7. 清理临时目录
    shutil.rmtree(TMP_DIR)
    print("== 完成。请在 VS 里编译 ARPGDemo_Server.sln 验证 ==")


if __name__ == "__main__":
    main()
