
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class dialogueOption : Luban.BeanBase
{
    public dialogueOption(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LineId = _buf.ReadInt();
        OptionIndex = _buf.ReadInt();
        OptionText = _buf.ReadString();
        NextLineIndex = _buf.ReadInt();
        IsTriggerEvent = _buf.ReadBool();
    }

    public static dialogueOption DeserializedialogueOption(ByteBuf _buf)
    {
        return new dialogueOption(_buf);
    }

    /// <summary>
    /// 选项编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属对话行 id
    /// </summary>
    public readonly int LineId;
    /// <summary>
    /// 在该行中的顺序
    /// </summary>
    public readonly int OptionIndex;
    /// <summary>
    /// 选项文本
    /// </summary>
    public readonly string OptionText;
    /// <summary>
    /// 跳转到的行号(-1 表示结束)
    /// </summary>
    public readonly int NextLineIndex;
    /// <summary>
    /// 结束时是否触发剧情收尾
    /// </summary>
    public readonly bool IsTriggerEvent;
   
    public const int __ID__ = 1115327597;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "lineId:" + LineId + ","
        + "optionIndex:" + OptionIndex + ","
        + "optionText:" + OptionText + ","
        + "nextLineIndex:" + NextLineIndex + ","
        + "isTriggerEvent:" + IsTriggerEvent + ","
        + "}";
    }
}

}

