
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class dialogue : Luban.BeanBase
{
    public dialogue(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TaskIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TaskIds.Add(_e0);}}
        CanSkip = _buf.ReadBool();
        AutoAdvance = _buf.ReadBool();
        AutoAdvanceDelay = _buf.ReadFloat();
    }

    public static dialogue Deserializedialogue(ByteBuf _buf)
    {
        return new dialogue(_buf);
    }

    /// <summary>
    /// 对话编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 结束后解锁的任务 id 列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> TaskIds;
    /// <summary>
    /// 是否可跳过
    /// </summary>
    public readonly bool CanSkip;
    /// <summary>
    /// 是否自动前进
    /// </summary>
    public readonly bool AutoAdvance;
    /// <summary>
    /// 自动前进延迟(秒)
    /// </summary>
    public readonly float AutoAdvanceDelay;
   
    public const int __ID__ = -233842216;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "taskIds:" + Luban.StringUtil.CollectionToString(TaskIds) + ","
        + "canSkip:" + CanSkip + ","
        + "autoAdvance:" + AutoAdvance + ","
        + "autoAdvanceDelay:" + AutoAdvanceDelay + ","
        + "}";
    }
}

}

