
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class dialogueLine : Luban.BeanBase
{
    public dialogueLine(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        DialogueId = _buf.ReadInt();
        LineIndex = _buf.ReadInt();
        SpeakerName = _buf.ReadString();
        Content = _buf.ReadString();
        Portrait = _buf.ReadString();
        Voice = _buf.ReadString();
        EndAfterThis = _buf.ReadBool();
    }

    public static dialogueLine DeserializedialogueLine(ByteBuf _buf)
    {
        return new dialogueLine(_buf);
    }

    /// <summary>
    /// 行编号（全局唯一）
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 所属对话 id
    /// </summary>
    public readonly int DialogueId;
    /// <summary>
    /// 在该对话中的顺序
    /// </summary>
    public readonly int LineIndex;
    /// <summary>
    /// 说话者名字
    /// </summary>
    public readonly string SpeakerName;
    /// <summary>
    /// 对话内容
    /// </summary>
    public readonly string Content;
    /// <summary>
    /// 立绘地址
    /// </summary>
    public readonly string Portrait;
    /// <summary>
    /// 语音地址
    /// </summary>
    public readonly string Voice;
    /// <summary>
    /// 本行后是否直接结束
    /// </summary>
    public readonly bool EndAfterThis;
   
    public const int __ID__ = 1350783468;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "dialogueId:" + DialogueId + ","
        + "lineIndex:" + LineIndex + ","
        + "speakerName:" + SpeakerName + ","
        + "content:" + Content + ","
        + "portrait:" + Portrait + ","
        + "voice:" + Voice + ","
        + "endAfterThis:" + EndAfterThis + ","
        + "}";
    }
}

}

