
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class driverDisk : Luban.BeanBase
{
    public driverDisk(ByteBuf _buf) 
    {
        DepotId = _buf.ReadInt();
        DepotName = _buf.ReadString();
        IconName = _buf.ReadString();
        InitLevel = _buf.ReadInt();
        InitMaxFill = _buf.ReadFloat();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);UpgradeMaterials = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); UpgradeMaterials.Add(_e0);}}
        DiskType = (DriverDiskType)_buf.ReadInt();
        BaseValue = _buf.ReadInt();
        AttackPercent = _buf.ReadFloat();
        DefensePercent = _buf.ReadFloat();
        HealthPercent = _buf.ReadFloat();
        BaoJiPercent = _buf.ReadFloat();
    }

    public static driverDisk DeserializedriverDisk(ByteBuf _buf)
    {
        return new driverDisk(_buf);
    }

    /// <summary>
    /// 驱动盘编号
    /// </summary>
    public readonly int DepotId;
    /// <summary>
    /// 驱动盘名称
    /// </summary>
    public readonly string DepotName;
    /// <summary>
    /// 图标资源名
    /// </summary>
    public readonly string IconName;
    /// <summary>
    /// 初始等级
    /// </summary>
    public readonly int InitLevel;
    /// <summary>
    /// 初始升级经验上限
    /// </summary>
    public readonly float InitMaxFill;
    /// <summary>
    /// 升级所需材料编号（逗号分隔）
    /// </summary>
    public readonly System.Collections.Generic.List<int> UpgradeMaterials;
    /// <summary>
    /// 驱动盘类型
    /// </summary>
    public readonly DriverDiskType DiskType;
    /// <summary>
    /// 基础数值
    /// </summary>
    public readonly int BaseValue;
    /// <summary>
    /// 攻击加成%
    /// </summary>
    public readonly float AttackPercent;
    /// <summary>
    /// 防御加成%
    /// </summary>
    public readonly float DefensePercent;
    /// <summary>
    /// 生命加成%
    /// </summary>
    public readonly float HealthPercent;
    /// <summary>
    /// 暴击加成%
    /// </summary>
    public readonly float BaoJiPercent;
   
    public const int __ID__ = 593806821;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "depotId:" + DepotId + ","
        + "depotName:" + DepotName + ","
        + "iconName:" + IconName + ","
        + "initLevel:" + InitLevel + ","
        + "initMaxFill:" + InitMaxFill + ","
        + "upgradeMaterials:" + Luban.StringUtil.CollectionToString(UpgradeMaterials) + ","
        + "diskType:" + DiskType + ","
        + "baseValue:" + BaseValue + ","
        + "attackPercent:" + AttackPercent + ","
        + "defensePercent:" + DefensePercent + ","
        + "healthPercent:" + HealthPercent + ","
        + "baoJiPercent:" + BaoJiPercent + ","
        + "}";
    }
}

}

