
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum DriverDiskType
    {
        /// <summary>
        /// 攻击
        /// </summary>
        Attack = 0,
        /// <summary>
        /// 防御
        /// </summary>
        Defense = 1,
        /// <summary>
        /// 生命
        /// </summary>
        Health = 2,
        /// <summary>
        /// 暴击
        /// </summary>
        BaoJi = 3,
    }

} 

