
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class materialData : Luban.BeanBase
{
    public materialData(ByteBuf _buf) 
    {
        MaterialId = _buf.ReadInt();
        Name = _buf.ReadString();
        IconName = _buf.ReadString();
        ExpValue = _buf.ReadFloat();
    }

    public static materialData DeserializematerialData(ByteBuf _buf)
    {
        return new materialData(_buf);
    }

    /// <summary>
    /// 材料/物品编号
    /// </summary>
    public readonly int MaterialId;
    /// <summary>
    /// 材料名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 图标资源名
    /// </summary>
    public readonly string IconName;
    /// <summary>
    /// 提供的经验数值
    /// </summary>
    public readonly float ExpValue;
   
    public const int __ID__ = -2116100751;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "materialId:" + MaterialId + ","
        + "name:" + Name + ","
        + "iconName:" + IconName + ","
        + "expValue:" + ExpValue + ","
        + "}";
    }
}

}

