
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class SkillInfo : Luban.BeanBase
{
    public SkillInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        JobId = _buf.ReadInt();
        Name = _buf.ReadString();
        Type = _buf.ReadInt();
        Icon = _buf.ReadString();
        CDTime = _buf.ReadFloat();
        Level = _buf.ReadInt();
        Desc = _buf.ReadString();
        Action = _buf.ReadInt();
        Hurt = _buf.ReadInt();
        HurtCount = _buf.ReadInt();
        HurtInterval = _buf.ReadInt();
        SpendMP = _buf.ReadInt();
        AtkDistance = _buf.ReadInt();
    }

    public static SkillInfo DeserializeSkillInfo(ByteBuf _buf)
    {
        return new SkillInfo(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 技能所属职业
    /// </summary>
    public readonly int JobId;
    /// <summary>
    /// 技能名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 技能类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 技能图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 技能CD
    /// </summary>
    public readonly float CDTime;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 技能描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 技能攻击Action
    /// </summary>
    public readonly int Action;
    /// <summary>
    /// 技能造成的伤害
    /// </summary>
    public readonly int Hurt;
    /// <summary>
    /// 技能造成伤害的次数
    /// </summary>
    public readonly int HurtCount;
    /// <summary>
    /// 技能伤害时间间隔
    /// </summary>
    public readonly int HurtInterval;
    /// <summary>
    /// 消耗的法力
    /// </summary>
    public readonly int SpendMP;
    /// <summary>
    /// 技能攻击距离
    /// </summary>
    public readonly int AtkDistance;
   
    public const int __ID__ = -300141953;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "JobId:" + JobId + ","
        + "Name:" + Name + ","
        + "Type:" + Type + ","
        + "Icon:" + Icon + ","
        + "CDTime:" + CDTime + ","
        + "Level:" + Level + ","
        + "Desc:" + Desc + ","
        + "Action:" + Action + ","
        + "Hurt:" + Hurt + ","
        + "HurtCount:" + HurtCount + ","
        + "HurtInterval:" + HurtInterval + ","
        + "SpendMP:" + SpendMP + ","
        + "AtkDistance:" + AtkDistance + ","
        + "}";
    }
}
}

