//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 gen_server.py 自动合并生成（Luban 表 + 手工 SkillInfo 表）。
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public TbSkillInfo TbSkillInfo {get; }
    public Tbdialogue Tbdialogue {get; }
    public TbdialogueLine TbdialogueLine {get; }
    public TbdialogueOption TbdialogueOption {get; }
    public TbdriverDisk TbdriverDisk {get; }
    public TbmaterialData TbmaterialData {get; }
    public TbtaskData TbtaskData {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbSkillInfo = new TbSkillInfo(loader("tbskillinfo"));
        Tbdialogue = new Tbdialogue(loader("tbdialogue"));
        TbdialogueLine = new TbdialogueLine(loader("tbdialogueline"));
        TbdialogueOption = new TbdialogueOption(loader("tbdialogueoption"));
        TbdriverDisk = new TbdriverDisk(loader("tbdriverdisk"));
        TbmaterialData = new TbmaterialData(loader("tbmaterialdata"));
        TbtaskData = new TbtaskData(loader("tbtaskdata"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbSkillInfo.ResolveRef(this);
        Tbdialogue.ResolveRef(this);
        TbdialogueLine.ResolveRef(this);
        TbdialogueOption.ResolveRef(this);
        TbdriverDisk.ResolveRef(this);
        TbmaterialData.ResolveRef(this);
        TbtaskData.ResolveRef(this);
    }
}

}
