
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum TaskType
    {
        /// <summary>
        /// 击败第一个敌人
        /// </summary>
        KillFirstEnemy = 0,
        /// <summary>
        /// 给每一个驱动盘都升一级
        /// </summary>
        UpgradeAllDriveDisk = 1,
    }

} 

