
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class taskData : Luban.BeanBase
{
    public taskData(ByteBuf _buf) 
    {
        TaskID = _buf.ReadInt();
        TaskDesc = _buf.ReadString();
        TaskType = (TaskType)_buf.ReadInt();
        TargetCount = _buf.ReadInt();
        IsUnlock = _buf.ReadBool();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);DepotIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); DepotIds.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);MaterialsId = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); MaterialsId.Add(_e0);}}
    }

    public static taskData DeserializetaskData(ByteBuf _buf)
    {
        return new taskData(_buf);
    }

    /// <summary>
    /// 任务唯一ID
    /// </summary>
    public readonly int TaskID;
    /// <summary>
    /// 任务描述
    /// </summary>
    public readonly string TaskDesc;
    /// <summary>
    /// 任务类型
    /// </summary>
    public readonly TaskType TaskType;
    /// <summary>
    /// 目标数量
    /// </summary>
    public readonly int TargetCount;
    /// <summary>
    /// 是否默认解锁
    /// </summary>
    public readonly bool IsUnlock;
    /// <summary>
    /// 驱动盘奖励id列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> DepotIds;
    /// <summary>
    /// 材料奖励id列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> MaterialsId;
   
    public const int __ID__ = -410628401;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "taskID:" + TaskID + ","
        + "taskDesc:" + TaskDesc + ","
        + "taskType:" + TaskType + ","
        + "targetCount:" + TargetCount + ","
        + "isUnlock:" + IsUnlock + ","
        + "depotIds:" + Luban.StringUtil.CollectionToString(DepotIds) + ","
        + "materialsId:" + Luban.StringUtil.CollectionToString(MaterialsId) + ","
        + "}";
    }
}

}

