
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbdialogueLine
{
    private readonly System.Collections.Generic.Dictionary<int, dialogueLine> _dataMap;
    private readonly System.Collections.Generic.List<dialogueLine> _dataList;
    
    public TbdialogueLine(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, dialogueLine>();
        _dataList = new System.Collections.Generic.List<dialogueLine>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            dialogueLine _v;
            _v = dialogueLine.DeserializedialogueLine(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, dialogueLine> DataMap => _dataMap;
    public System.Collections.Generic.List<dialogueLine> DataList => _dataList;

    public dialogueLine GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public dialogueLine Get(int key) => _dataMap[key];
    public dialogueLine this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

