
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class Tbdialogue
{
    private readonly System.Collections.Generic.Dictionary<int, dialogue> _dataMap;
    private readonly System.Collections.Generic.List<dialogue> _dataList;
    
    public Tbdialogue(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, dialogue>();
        _dataList = new System.Collections.Generic.List<dialogue>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            dialogue _v;
            _v = dialogue.Deserializedialogue(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, dialogue> DataMap => _dataMap;
    public System.Collections.Generic.List<dialogue> DataList => _dataList;

    public dialogue GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public dialogue Get(int key) => _dataMap[key];
    public dialogue this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

