
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbdialogueOption
{
    private readonly System.Collections.Generic.Dictionary<int, dialogueOption> _dataMap;
    private readonly System.Collections.Generic.List<dialogueOption> _dataList;
    
    public TbdialogueOption(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, dialogueOption>();
        _dataList = new System.Collections.Generic.List<dialogueOption>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            dialogueOption _v;
            _v = dialogueOption.DeserializedialogueOption(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, dialogueOption> DataMap => _dataMap;
    public System.Collections.Generic.List<dialogueOption> DataList => _dataList;

    public dialogueOption GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public dialogueOption Get(int key) => _dataMap[key];
    public dialogueOption this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

