
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbdriverDisk
{
    private readonly System.Collections.Generic.Dictionary<int, driverDisk> _dataMap;
    private readonly System.Collections.Generic.List<driverDisk> _dataList;
    
    public TbdriverDisk(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, driverDisk>();
        _dataList = new System.Collections.Generic.List<driverDisk>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            driverDisk _v;
            _v = driverDisk.DeserializedriverDisk(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.DepotId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, driverDisk> DataMap => _dataMap;
    public System.Collections.Generic.List<driverDisk> DataList => _dataList;

    public driverDisk GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public driverDisk Get(int key) => _dataMap[key];
    public driverDisk this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

