
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbmaterialData
{
    private readonly System.Collections.Generic.Dictionary<int, materialData> _dataMap;
    private readonly System.Collections.Generic.List<materialData> _dataList;
    
    public TbmaterialData(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, materialData>();
        _dataList = new System.Collections.Generic.List<materialData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            materialData _v;
            _v = materialData.DeserializematerialData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.MaterialId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, materialData> DataMap => _dataMap;
    public System.Collections.Generic.List<materialData> DataList => _dataList;

    public materialData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public materialData Get(int key) => _dataMap[key];
    public materialData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

