
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbSkillInfo
{
    private readonly System.Collections.Generic.Dictionary<int, SkillInfo> _dataMap;
    private readonly System.Collections.Generic.List<SkillInfo> _dataList;
    
    public TbSkillInfo(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, SkillInfo>(n);
        _dataList = new System.Collections.Generic.List<SkillInfo>(n);
        for(int i = n ; i > 0 ; --i)
        {
            SkillInfo _v;
            _v = global::cfg.SkillInfo.DeserializeSkillInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SkillInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<SkillInfo> DataList => _dataList;

    public SkillInfo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public SkillInfo Get(int key) => _dataMap[key];
    public SkillInfo this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

