
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbtaskData
{
    private readonly System.Collections.Generic.Dictionary<int, taskData> _dataMap;
    private readonly System.Collections.Generic.List<taskData> _dataList;
    
    public TbtaskData(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, taskData>();
        _dataList = new System.Collections.Generic.List<taskData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            taskData _v;
            _v = taskData.DeserializetaskData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.TaskID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, taskData> DataMap => _dataMap;
    public System.Collections.Generic.List<taskData> DataList => _dataList;

    public taskData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public taskData Get(int key) => _dataMap[key];
    public taskData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

